### ISSUE TITLE
Add Support for Older Browsers

### ISSUE THREAD

**Issue by nchapman** [mozilla/fxa-content-server#136]
We don't have a final list of browsers to support, but we've tentatively decided to support back to IE 8 (#105), so we should fix the incompatible bits.
- [x] Replace Function.prototype.bind (#108).
- [x] Remove incompatibility message that currently exists for < IE 10.
- [x] Evaluate pushState usage.
- [x] `switch` is a reserved word (in router.js - noted in #179)
- [x] `window.navigator.language` is undefined in IE8 (#183)
- [x] HTML5 form validation unsupported in IE8 (#185)
- [x] require('gherkin', ...) returns `undefined` in IE8 (#186)
