### ISSUE TITLE
FxA Sync iframe flow

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-content-server#2101]
So that I can connect my Firefox with Sync from more places, as a Firefox user, I want to be able to authenticate (register or login) from an iframe.

------------------------------------------------

stomlinson's list of sub work:
* [x] ~~A bi-directional WebChannel is needed to communicate with the browser. (#2231, PR #2358)~~
* [x] ~~An AuthenticationBroker that can communicate with Sync using the bi-directional WebChannel (#2359, PR #2237)~~
* [x] ~~A "Chromeless" UI is needed - one without the X and Firefox logo (#2198, PR #2236)~~
* [x] ~~The content server must allow `/` to be iframed. The iframe's parent origin needs to be checked to ensure we trust the framer. The OAuth flow uses the `client_id`, then checks the parent origin is the same as is registered for the `client_id`. This is not an OAuth flow. (#2242, PR #2364)~~
* [x] ~~The content server should decide whether to show `/signin`, `/signup`, or `/settings` - this can be done by visiting `/`. Expected behavior needs clarification. (#2197)~~
* [x] ~~Determine the URL API - how does the relier indicate:~~
  * ~~Chromeless UI~~
  * ~~Are in an iframe (OAuth reliers use context=iframe)~~
  * ~~Should use the WebChannel to communicate (webChannelId=sync possibly?)~~
  * ~~Is using Sync (currently we use service=sync&context=fx_desktop_v1) and no "signout" link should be displayed on settings.~~
  * ~~A possibility: https://accounts.firefox.com/?service=sync&context=iframe~~
* [x] ~~Unlike the normal Sync flow, the "settings" page should be displayed after sign in, and the "account verified" page should be displayed in the original tab after account verification. (#2674, PR #2687)~~
* [x] ~~TOS/PP rendering results in a scroll bar in the center of the page - should TOS/PP agreements be loaded in a new tab? YES! (#2351, PR #2643)~~
* [x] ~~Links in iframed TOS/PP replace content - (#1968, PR #2337)~~
* [x] ~~Channel timeout needs to go - (#2146, PR #2358)~~
* [x] ~~Disable the browser's "remember password" after signin/signup. (#2373, PR #2374, https://bugzilla.mozilla.org/show_bug.cgi?id=1173688)~~
* [x] ~~Remove the title for sync/iframe (#2565, PR #2593)~~
* [x] ~~Pass `campaign` and `entrypoint` to the verification page (#2491, PR #2688)~~
* [x] ~~Pass `uniqueUserId` to the verification page to tie together signup/verification metrics (#2491, PR #2756)~~
* [x] ~~Determine whether the user is part of metrics in a more deterministic fashion (#2491, #2780)~~
* [x] ~~Notify the parent when the content height changes (#2566, PR #2594)~~
* [x] ~~Possibly consume GA query parameters and report them to metrics (#2579, PR #2689, PR #2779)~~
* [x] ~~Send consumed GA stats to Google (#2782, PR #2787)~~
* [x] ~~Prevent sign out link from showing on the settings page for accounts authenticated from firstrun (#2658, PR #2853)~~
* [x] ~~Fix partially hidden body (#2669, PR #2675)~~
* [x] ~~Notify iframe parent on initial screen load, login, and verification (#2704, PR #2705)~~
* [x] ~~Fix padding around marketing snippet on verification page (#2709, PR #2798)~~
* [x] ~~send a signal to the parent on successful signup (#2790, PR #2793)~~
* [ ] send a signal to the parent on unsuccessful signup (#2791)
* [ ] cancel in the merge warning should prevent the signup/signin (#2844, PR #2845)

Bugzilla tracking bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1150231

**Comment by shane-tomlinson** [comment]
Can we get more info about the use case? Sync is pretty specific to the browser, supporting signin to Sync from arbitrary sites seems like it could be a big ball of yuck.

**Comment by ryanfeeley** [comment]
Only from the stub installer, the onboarding tour, or authorized sites. I had a discussion with Michael Verdi this morning and realized how offering account registration during UI tours is not terribly helpful.

**Comment by vladikoff** [comment]
This might also work as a standalone component and not be part of the content server.

**Comment by ckarlof** [comment]
This could be implemented by the FxAccounts.jsm component in the browser opening up a generic WebChannel to listen to messages from `accounts.firefox.com`. Bugzilla bug about this: https://bugzilla.mozilla.org/show_bug.cgi?id=998051, but filed before WebChannel landed. It should be fairly straightforward. :) 

Open questions:
* what kind of broker does the enclosing page trigger (Sync vs OAuth)
* do browser content scripts get added to iframes (this is how WebChannels work)?

**Comment by shane-tomlinson** [comment]
ref #2178, #2198

**Comment by shane-tomlinson** [comment]
ref #2231

**Comment by shane-tomlinson** [comment]
Sub work:
* A bi-directional WebChannel (#2231) is needed to communicate with the browser.
* Check the iframe parent is one we trust.
* A "Chromeless" UI is needed - one without the X and Firefxo logo (#2198)
* The iframe's parent origin needs to be checked to ensure we trust the framer.
* The content server should decide whether to show `/signin` or `/signup` - this can be done by visiting `/`.
* Determine the URL API - how does the relier indicate:
  * Chromeless UI
  * Are in an iframe (OAuth reliers use context=iframe)
  * Should use the WebChannel to communicate (webChannelId=sync possibly?)
  * Is using Sync (currently we use service=sync&context=fx_desktop_v1) and no "signout" link should be displayed on settings.
  * A possibility: https://accounts.firefox.com/?service=sync&webChannelId=sync&context=fx_desktop_v2
* Unlike the normal Sync flow, the "settings" page should be displayed after sign in, and the "account verified" page should be displayed in the original tab after account verification.
* TOS/PP rendering results in a scroll bar in the center of the page - should TOS/PP agreements be loaded in a new tab?
* Channel timeout needs to go - #2146 affects Fx Desktop when using WebChannels.

**Comment by shane-tomlinson** [comment]
cc @habber

**Comment by shane-tomlinson** [comment]
Ref https://github.com/mozilla/fxa-content-server/issues/2238#issuecomment-86170861

**Comment by rfk** [comment]
> The content server should decide whether to show /signin or /signup - this can be done by visiting /.

We may have bikeshedded this already, so appologies if I just don't remember it.  But does it make sense to include some sort of verb in the URL for all oauth redirects and reserve `/` for a user-facing landing page?  I'm thinking something generic like `/connect` or `/authenticate` or even just `/oauth`.

I get a vague something-not-quite-right feeling about having the oauth redirect dance land at the root of the site, although I don't feel strongly about it and don't want to derail what you've got going on here.

(Also we'll need an issue in fxa-oauth-server to adjust the meaning of the `action` parameter in https://github.com/mozilla/fxa-oauth-server/blob/master/docs/api.md#request-parameters-4)

**Comment by shane-tomlinson** [comment]
>  But does it make sense to include some sort of verb in the URL for all oauth redirects and reserve / for a user-facing landing page? I'm thinking something generic like /connect or /authenticate or even just /oauth.
>
> I get a vague something-not-quite-right feeling about having the oauth redirect dance land at the root of the site, although I don't feel strongly about it and don't want to derail what you've got going on here.

I had the same thought last night. The firstrun/Sync flow is not going to be an OAuth relier, so sending the user to `/` seems alright. For OAuth reliers, sending to `/` does feel like a hack. Sending them to `/oauth` or `/oauth/do-the-right-thing` would be better.

**Comment by issues-bouncer** [comment]
Hey @shane-tomlinson, you have been assigned on this issue for more than 14 days!
Maybe you should consider un-assigning yourself and let other people try to solve this issue.

**Comment by shane-tomlinson** [comment]
@issues-bouncer - no.

**Comment by shane-tomlinson** [comment]
There is only one item in this list that does not have a PR, #2791. I'm going to close this out as "this is ready enough to ship."

**Comment by rfk** [comment]
\o/
