### ISSUE TITLE
Fennec integration tracking issue.

### ISSUE THREAD

**Issue by ncalexan** [mozilla/fxa-content-server#2771]
Two requests:
* first, communicate to the browser when the account is verified.  I understand this doesn't replace polling on Desktop or timed background syncing on Fennec, because the about:accounts page may be closed.  But we have to get in the habit of helping the browser do the right thing.
* second, make /signup_completed (and /signin_completed, if it exists) redirect to /settings or have some concrete action to take.  I have no buttons or links with ?context=iframe&service=sync, leaving just a tab with no action to be taken.

**Comment by shane-tomlinson** [comment]
@ncalexan - which environment are you making this request for? There are a couple of ways to implement your request, I want to make sure we do the right thing and don't cause unexpected change of behavior for existing clients.

**Comment by shane-tomlinson** [comment]
@ncalexan - BTW, I'm assuming fennec.

**Comment by shane-tomlinson** [comment]
Side note, if a new context is needed, we will need a new column in https://docs.google.com/spreadsheets/d/16Uhb8vtGB_-krMbzaq0b3XYvTWePi_xgIElL7dquohA and corresponding functional tests.

**Comment by mhammond** [comment]
IIUC, Nick would like a "notification" (ie, event or channel message) as the content server transitions to the /signup_complete page, which indicates the user is verified. Or to put it another way, something that would mean the polling we do for the verified flag could be considered a fallback because most of the time we would not get a notification directly from the content server of the state change.

**Comment by mhammond** [comment]
*sigh* -  "because most of the time we *would* get a notification directly from the content server of the state change"

**Comment by shane-tomlinson** [comment]
Your video gave me all the context I need, thanks @ncalexan!

**Comment by shane-tomlinson** [comment]
@ncalexan - fennec speaks the WebChannel variant of the messaging protocol, correct?

**Comment by shane-tomlinson** [comment]
> first, communicate to the browser when the account is verified. I understand this doesn't replace polling on Desktop or timed background syncing on Fennec, because the about:accounts page may be closed. But we have to get in the habit of helping the browser do the right thing.

@ncalexan - When embedded in about:accounts for desktop, the content server does not poll. Having both the browser and the content server poll was our highest source of load. For about:accounts, the content server redirects from the signup page to the "confirm your email address" page, and stops. At this point, the browser polls in the background. If the about:accounts page is still open when the browser discovers the account is verified, the browser hides the content server and displays its own content.

For Fennec, you want the confirm screen to poll, and when the user opens the verification email, if the tab with the confirm screen is still open, it should transition to /settings?

> second, make /signup_completed (and /signin_completed, if it exists) redirect to /settings or have some concrete action to take. I have no buttons or links with ?context=iframe&service=sync, leaving just a tab with no action to be taken.

For the verification tab, desktop stops at /signup_complete. We did this because an automatic transition from /signup_complete to /settings gave users little opportunity to read the /signup_complete content, including the marketing material (that says "Go Download Firefox for Android!") that pushes your product.

We could add a link to the /signup_complete page that allows the user to go to /settings, which might be a good idea for Desktop as well.

@ryanfeeley - can you help with the Fennec flows to ensure both a good experience and consistency with our other products?

@ncalexan - I added a new column to the [giant flow doc](https://docs.google.com/spreadsheets/d/16Uhb8vtGB_-krMbzaq0b3XYvTWePi_xgIElL7dquohA/edit). We will need to fill out the column labelled FxAndroid/Sync with each of the possible scenarios so that we can ensure expectations are understood, that the code matches the expectations, and that we have functional tests that test all of the above.

**Comment by shane-tomlinson** [comment]
@ncalexan - for Fennec, what do you think about using `context=fx_android_v1` instead of `context=iframe` or `context=fx_desktop_v1`? That way we can completely isolate the Fennec related behaviors and modify them without causing problems for other environments.

**Comment by ncalexan** [comment]
On Thu, Jul 30, 2015 at 5:54 AM, Shane Tomlinson <notifications@github.com>
wrote:

> @ncalexan <https://github.com/ncalexan> - fennec speaks the WebChannel
> variant of the messaging protocol, correct?
>
Correct, or at least, it will.

**Comment by ncalexan** [comment]
On Thu, Jul 30, 2015 at 6:27 AM, Shane Tomlinson <notifications@github.com>
wrote:

> @ncalexan <https://github.com/ncalexan> - for Fennec, what do you think
> about using context=fx_android_v1 instead of context=iframe or
> context=fx_desktop_v1? That way we can completely isolate the Fennec
> related behaviors and modify them without causing problems for other
> environments.
>
I absolutely support this.  But I prefer "fx_fennec_v1" rather than
"android", which feels too generic.

**Comment by rfk** [comment]
> and /signin_completed, if it exists

Currently a successful signin goes straight to settings without an intermediate screen.  We're working through some tweaks to that for the first-run flow atm (see #2945, #3021), and I kinda like the idea of an intermediate "you signed in, good job!" screen for embedded device flows like this.  Would such a screen be sensible/useful in the android case as well, as a success state?

**Comment by ncalexan** [comment]
On Thu, Sep 3, 2015 at 7:42 PM, Ryan Kelly <notifications@github.com> wrote:

> and /signin_completed, if it exists
>
> Currently a successful signin goes straight to settings without an
> intermediate screen. We're working through some tweaks to that for the
> first-run flow atm (see #2945
> <https://github.com/mozilla/fxa-content-server/issues/2945>, #3021
> <https://github.com/mozilla/fxa-content-server/pull/3021>), and I kinda
> like the idea of an intermediate "you signed in, good job!" screen for
> embedded device flows like this. Would such a screen be sensible/useful in
> the android case as well, as a success state.
>
You read my mind.  In discussions with @antlam, we focused on connecting
the fxa-content-server "success" transition (you signed in) to the user's
intent being fulfilled (you're syncing).  @antlam is not a fan of
interstitials and wanted an animated notification icon to appear.  (This
mirrors a new download on Fennec and also the "Sync will start" dropdown on
Desktop.)  I'd like to do that animated notification icon *and* have the
fxa-content-server say "you're connected".

Worth noting this applies to both sign up/sign in and force_reauth:
"Welcome" and "Welcome back", respectively.

@stomlinson, @zaach: sorry I didn't know of this when we talked about
Fennec asks.  Do you have thoughts about this?

**Comment by shane-tomlinson** [comment]
ref #2771

**Comment by shane-tomlinson** [comment]
@ncalexan - @zaach and I are wondering - do you want a new interstitial screen, or an animation on the settings screen post-signup/signin/whatever?

**Comment by shane-tomlinson** [comment]
@ncalexan - also, what's the time frame for this?

**Comment by vladikoff** [comment]
@shane-tomlinson also see https://mozilla.aha.io/features/FXA-27

**Comment by ncalexan** [comment]
On Wed, Sep 9, 2015 at 12:53 PM, Shane Tomlinson <notifications@github.com>
wrote:

> @ncalexan <https://github.com/ncalexan> - @zaach
> <https://github.com/zaach> and I are wondering - do you want a new
> interstitial screen, or an animation on the settings screen
> post-signup/signin/whatever?
>
/signup goes (after verification) to a nice check-box and {you're ready to
Sync}.

I'd like /signin to end up with a nice check-box and {Welcome to Sync //
Firefox will begin syncing momentarily}.  I'd like force_auth to end up
with a nice check-box and {Welcome back // Firefox will resume syncing
momentarily}.

See
https://www.lucidchart.com/documents/edit/92d0ec74-a2af-40b8-b714-6db99149e39c/1,
the tab (mis!)labeled "Android Choose What to Sync".

**Comment by ncalexan** [comment]
On Wed, Sep 9, 2015 at 12:58 PM, Shane Tomlinson <notifications@github.com>
wrote:

> @ncalexan <https://github.com/ncalexan> - also, what's the time frame for
> this?
>
Soon-ish.  We'll turn this on in Nightly in the next week (end of 43) or
two (beginning of 44), but it doesn't need to be polished until 43 hits
Beta, which is 6-7 weeks out.  I will update dev-fxacct on progress today.

**Comment by shane-tomlinson** [comment]
User facing work to be done:

* [ ] Allow the `signin` screen to transition to a `signin_complete` screen after a successful signin.
* [ ] Allow the `force_auth` screen to transition to a `force_auth_complete` screen after a successful force-auth signin.
* [ ] Allow the `confirm` screen to transition to a `signup_complete` screen after a user successfully verifies their account.
* [ ] Add/Update the `*_complete` screens with a `Sync Preferences` button and flow specific text:
  * [ ] `signin_complete` - title: `Welcome to Sync`, body text: `Firefox Sync will begin momentarily`
  * [ ] `force_auth_complete` - title: `Welcome back`, body text: `Firefox Sync will resume momentarily`
  * [ ] `signup_complete` - title: `Account verified`, body text: `You are now ready to use Firefox Sync`
* [ ] Handle the `Sync Preferences` button.

Non user-facing work to be done:
* [ ] Send a WebChannel message to Fennec to open the Sync preferences when the user presses the `Sync Preferences` button.
* [ ] Update the [flow document](https://docs.google.com/spreadsheets/d/16Uhb8vtGB_-krMbzaq0b3XYvTWePi_xgIElL7dquohA)
* [ ] Functional tests.

**Comment by ncalexan** [comment]
This is awesome!  Consider separating the *Sync Preferences* button into a
follow-up, since it's flow polish.  Your call.

**Comment by shane-tomlinson** [comment]
I'm closing this since the bulk of user facing work is released and separate issues are filed for the last remaining issues.

**Comment by vladikoff** [comment]
Woohoo!
