### ISSUE TITLE
"devices" view work breakdown

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#3250]
See https://github.com/mozilla/fxa/blob/master/features/FxA-16-devices-view/README.md

* [x] Add methods to communicate w/ auth server fxa-js-client - (https://github.com/mozilla/fxa-js-client/issues/176, PR https://github.com/mozilla/fxa-js-client/pull/177)
* [ ] Add "devices" view in the /settings page. (#3251, PR #3274)
* [ ] Add WebChannel communication to browser if user disconnects or changes the name of the current device. (#3252)
  * [ ] Update the WebChannel doc
* [ ] Handshake with browser to determine current device name and ID. (#3252)
* [ ] Accept WebChannel messages from the browser to handle current device name change, disconnect. (#3252)

**Comment by vladikoff** [comment]
from mtg: we should somehow move this to the features repo and close this

**Comment by vladikoff** [comment]
Landed in https://github.com/mozilla/fxa/commit/311932df14163344f064747692f0987b4fddc762
