### ISSUE TITLE
Implement Photon styling

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-content-server#6083]
This is a tracking bug until we get designs and priorities from @ryanfeeley and @changecourse.

child of mozilla/fxa#294

## Global

* [x] P1: Email-First Auth Flow – currently in flight (#6126, #6187)
* [x] P1: System fonts instead of Fira – providing better consistency cross-platform and allowing for additional font weights without sacrificing performance (via custom fonts)
(https://furbo.org/2018/03/28/system-fonts-in-css/)  (#6146)
* [x] P1: Primary Button (color, height, font size) – alignment to Photon spec (#6155)
* [x] P1: Removal of Card on mobile viewport – By removing the white card previously around the login container, we are able to create better contrast between input fields and their corresponding background (#6158)
* [x] P2: Text Fields (size, focus state) – alignment to Photon spec
* [x] P2: Font Weight Variance – refer to designs for use of different font weights throughout to establish a better typographic hierarchy throughout the flow (#6185)
* [x] P2: Hyperlink Color – Blue60
* [x] P2: Hyperlink Placement – Centered below primary button, consistent padding (#6185)
* [x] P2: Logo Sizing – 56x56 
* [x] P2: Header, Subheader (Size & Padding) – Adjusting to photon spec
* [x] P3: Keyboard Type – on age verification question, default to numeric keypad (#6133)
* [ ] P3: Host the confirmation message within Lockbox – rather than in a browser, so the user doesn’t have to navigate back 

## Create Account

* [x] P1: Top align error validation tooltips for mobile viewports – the keyboard obfuscates error messages below the form field (#6188, #6195)
* [x] P1: Revised approach to hide/show password with icons - #6184
* [x] P2: Use Darker Red for validation errors to improve accessibility – Red60
* [x] P2: Confirm padding and positioning of tooltips – alignment to designs
* [x] P2: Display of Email Address (Read-Only) – alignment to designs
* [ ] P2: Padding between Password & Age Verification fields – alignment to designs (#6015)
* [ ] P3: Inline validation for password mismatch rather than on submission

## Sign In

* [x] P2: Returning User Lockup (avatar, email address, change email link) – moving the profile information into its own card allows us to pair the ability to switch to a different account within the context of the profile that is displayed, rather than at the base of the auth form (#6126, #6187)
* [x] P2: Revise the Email Confirmation Screen – to align with other parts of the FxA flow (#6185)
* [ ] P3: Revise the Email for Confirming Sign-in – to align with other parts of the FxA flow (https://github.com/mozilla/fxa-auth-server/issues/2448)
* [ ] P3: Revise the Confirmation Message – to align with other parts of the FxA flow (#6218)

## Other
* [ ] Provide a button to “Go to Lockbox” from the confirmation screen – as shown in the designs via InVision (#6217)

**Comment by shane-tomlinson** [comment]
Current recommendations: https://docs.google.com/document/d/1rk6FeveA-ULquR06adwWNY0BSrTCtH7fReAliRA_Pac/edit?ts=5ad7c39c#

**Comment by shane-tomlinson** [comment]
I have opened follow on bugs for each of the remaining items, I am moving this to the backlog.

**Comment by devinreams** [comment]
@shane-tomlinson Awesome work getting this all in place! 

Sorry if this is not a helpful place to put this but since it was related to this work I figured I'd consolidate all the little stuff we noticed and just make sure you were aware of it, if not already:

1. PI noticed the "Sign In" button text is not centered at certain (narrow) breakpoints and is instead left aligned. I believe this is already known and tracked here: https://bugzilla.mozilla.org/show_bug.cgi?id=1465392

2. When tapping into fields (username, password, 2FA code) sometimes the webview zooms in, perhaps related to the [viewport](https://developer.apple.com/library/content/documentation/AppleApplications/Reference/SafariWebContent/UsingtheViewport/UsingtheViewport.html) meta tag not fixing it to a 1.0 scale?

3. The 2FA code form input uses the default keyboard (type=text) but may be a good candidate for a numeric keypad ([type=number](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number)) since its really helpful on mobile devices that do something with that, if not already considered.

4. The "tap to reveal" eye icon that toggles the plaintext password may be considered hard (or potentially impossible?) to toggle with a screen reader like VoiceOver on iOS.

Thanks again for all the refactor work here, hopefully this is helpful. 😁

**Comment by shane-tomlinson** [comment]
Thanks @devinreams, I am opening related issues for each of these.

re the viewport meta-tag, not disabling zoom was an explicit decision discussed in https://github.com/mozilla/fxa-content-server/issues/2228. I'm open to revisiting that discussion though I am extremely reluctant to completely disable zoom for users on mobile devices that need it.

**Comment by devinreams** [comment]
Awesome! Thanks for the quick review and responses/issues, @shane-tomlinson. 🙇 

>I am extremely reluctant to completely disable zoom for users on mobile devices that need it.

Agreed, there's some side-effect of tapping into inputs that may be zooming unintentionally but that seems worth keeping over disabling zoom. Thanks for the link and context 👍

**Comment by vladikoff** [comment]
@shane-tomlinson can this be closed?

**Comment by shane-tomlinson** [comment]
There are still a few more items to do though there are separate issues open for each of them. We can close this.
